services:
    php:
        image: tugboatqa/php:apache
        default: true
        commands:
            init: ln -snf "${TUGBOAT_ROOT}/web" "${DOCROOT}"
    mysql:
        image: tugboatqa/mysql:5
        commands:
            init: zcat .tugboat/tugboat.sql.gz | mysql tugboat

