services:
    php:
        image: tugboatqa/php:apache
        default: true
        commands:
            init:
                - docker-php-ext-install mysqli
                - ln -snf "${TUGBOAT_ROOT}/web" "${DOCROOT}"
    mysql:
        image: tugboatqa/mysql:5
        checkout: true
        commands:
            init: zcat .tugboat/tugboat.sql.gz | mysql tugboat

